### ISSUE TITLE
More GCode commands not taken into account by CharlyGraal

### ISSUE THREAD

**Issue by romdicos** [fra589/charly_post#1]
Hello,
First, thanks for this great piece of code. That's really useful! I however think that GPilot (GP) is more limited in term of commands and there's a number of them that aren't reconnized by the software even after using your postprocessing code.

For instance  'G21', 'G28', 'G34', 'G43', 'M09', 'G40', 'G41', 'G42', 'M08' are unknown code in GPilot. I believe they should be post processed as well so the code can be imported in GP. 

Also I think that codes 'G54', 'G91' and 'G17' should be removed and M30 should be replaced by M2.
I actually started myself to write a really basic python function so I could have SolidCam code imported by GC (see attached). This code is however too basic and does not handle tool changes and change in tool speed. So I use this code to postprocess the code exported from FreeCAM with your postprocessing, and it works for me. Maybe some of it could (should?) be included in your PP code? Or do I misuse your code?
FYI, I have version 5.1.0.39 of GP installed

[postProcessor-CG.zip](https://github.com/fra589/charly_post/files/2680528/postProcessor-CG.zip)

**Comment by fra589** [comment]
Hi @romdicos,  
Thanks for your feedback about this first version of charly_post, I will take it into account for the next updates.
I rapidly wrote this post processor since I had a piece to mill on the [Bordeaux Cho@bit](https://www.iut.u-bordeaux.fr/cohabit/) Fablab's Charly robot. Sure, it asks to be perfected  :gem:, but It worked for me for a full CNC milling and drilling with tool change  :ok_hand:.
For the moment, I work on my other projects (cn5X & grbl_Mega_5X) so, I keep this issue and the interesting updates proposed to be done for the future.
By the way, this is a post processor writed for the [FreeCAD](https://www.freecadweb.org/) Path Module.
- Since there are not supported by FreeCAD, G20/G21 are aleready post processed and translated to G70/71 corresponding GP codes.
- 'G98', 'G80', 'G17' are removed GCode commands, you can add your own by update the list on line number 99 of the script charly_post.py.
- Other GCode you tell about are not used by FreeCAD, unless you add it manualy :  

List of currently FreeCAD supported GCode commands :  

Command | Description | Supported Arguments
-- | -- | --
G0 | rapid move | X,Y,Z,A,B,C
G1 | normal move | X,Y,Z,A,B,C
G2 | clockwise arc | X,Y,Z,A,B,C,I,J,K
G3 | counterclockwise arc | X,Y,Z,A,B,C,I,J,K
G81, G82, G83 | drill | X,Y,Z,R,Q
G90 | absolute coordinates |  
G91 | relative coordinates |  
(Message) | comment |  

All those commands are post processed.

@++;  
Gauthier.
